# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Mon Aug  4 22:24:11 2014
#      by: PyQt4 UI code generator 4.9.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(320, 240)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayoutWidget = QtGui.QWidget(self.centralwidget)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(0, 0, 321, 231))
        self.horizontalLayoutWidget.setObjectName(_fromUtf8("horizontalLayoutWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.horizontalLayoutWidget)
        self.horizontalLayout.setMargin(0)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.buttonBack = QtGui.QPushButton(self.horizontalLayoutWidget)
        self.buttonBack.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Fixed, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonBack.sizePolicy().hasHeightForWidth())
        self.buttonBack.setSizePolicy(sizePolicy)
        self.buttonBack.setMinimumSize(QtCore.QSize(40, 0))
        self.buttonBack.setText(_fromUtf8(""))
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(_fromUtf8(":/back/back.png")), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.buttonBack.setIcon(icon)
        self.buttonBack.setObjectName(_fromUtf8("buttonBack"))
        self.horizontalLayout.addWidget(self.buttonBack)
        self.stackedWidget = QtGui.QStackedWidget(self.horizontalLayoutWidget)
        self.stackedWidget.setFrameShadow(QtGui.QFrame.Raised)
        self.stackedWidget.setObjectName(_fromUtf8("stackedWidget"))
        self.pageMain = QtGui.QWidget()
        self.pageMain.setObjectName(_fromUtf8("pageMain"))
        self.gridLayoutWidget = QtGui.QWidget(self.pageMain)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(0, 0, 271, 221))
        self.gridLayoutWidget.setObjectName(_fromUtf8("gridLayoutWidget"))
        self.gridLayout = QtGui.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtGui.QLayout.SetDefaultConstraint)
        self.gridLayout.setSpacing(6)
        self.gridLayout.setMargin(0)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonEmpty4 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonEmpty4.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEmpty4.sizePolicy().hasHeightForWidth())
        self.buttonEmpty4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonEmpty4.setFont(font)
        self.buttonEmpty4.setObjectName(_fromUtf8("buttonEmpty4"))
        self.gridLayout.addWidget(self.buttonEmpty4, 2, 1, 1, 1)
        self.buttonEmpty2 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonEmpty2.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEmpty2.sizePolicy().hasHeightForWidth())
        self.buttonEmpty2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonEmpty2.setFont(font)
        self.buttonEmpty2.setObjectName(_fromUtf8("buttonEmpty2"))
        self.gridLayout.addWidget(self.buttonEmpty2, 1, 1, 1, 1)
        self.buttonEmpty1 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonEmpty1.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEmpty1.sizePolicy().hasHeightForWidth())
        self.buttonEmpty1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonEmpty1.setFont(font)
        self.buttonEmpty1.setObjectName(_fromUtf8("buttonEmpty1"))
        self.gridLayout.addWidget(self.buttonEmpty1, 1, 0, 1, 1)
        self.buttonRadio = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRadio.sizePolicy().hasHeightForWidth())
        self.buttonRadio.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonRadio.setFont(font)
        self.buttonRadio.setObjectName(_fromUtf8("buttonRadio"))
        self.gridLayout.addWidget(self.buttonRadio, 0, 0, 1, 1)
        self.buttonEmpty3 = QtGui.QPushButton(self.gridLayoutWidget)
        self.buttonEmpty3.setEnabled(False)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonEmpty3.sizePolicy().hasHeightForWidth())
        self.buttonEmpty3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonEmpty3.setFont(font)
        self.buttonEmpty3.setObjectName(_fromUtf8("buttonEmpty3"))
        self.gridLayout.addWidget(self.buttonEmpty3, 2, 0, 1, 1)
        self.buttonDrinks = QtGui.QPushButton(self.gridLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonDrinks.sizePolicy().hasHeightForWidth())
        self.buttonDrinks.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonDrinks.setFont(font)
        self.buttonDrinks.setObjectName(_fromUtf8("buttonDrinks"))
        self.gridLayout.addWidget(self.buttonDrinks, 0, 1, 1, 1)
        self.stackedWidget.addWidget(self.pageMain)
        self.pageUsers = QtGui.QWidget()
        self.pageUsers.setObjectName(_fromUtf8("pageUsers"))
        self.gridLayoutWidget_2 = QtGui.QWidget(self.pageUsers)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(0, 0, 271, 221))
        self.gridLayoutWidget_2.setObjectName(_fromUtf8("gridLayoutWidget_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtGui.QLayout.SetMaximumSize)
        self.gridLayout_2.setContentsMargins(-1, -1, 3, -1)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.stackedWidget.addWidget(self.pageUsers)
        self.pageDrinks = QtGui.QWidget()
        self.pageDrinks.setObjectName(_fromUtf8("pageDrinks"))
        self.verticalLayoutWidget = QtGui.QWidget(self.pageDrinks)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(0, 10, 271, 211))
        self.verticalLayoutWidget.setObjectName(_fromUtf8("verticalLayoutWidget"))
        self.verticalLayout = QtGui.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setSpacing(10)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.labelSoft = QtGui.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelSoft.setFont(font)
        self.labelSoft.setObjectName(_fromUtf8("labelSoft"))
        self.horizontalLayout_3.addWidget(self.labelSoft)
        self.lcdCounterWater = QtGui.QLCDNumber(self.verticalLayoutWidget)
        self.lcdCounterWater.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdCounterWater.setNumDigits(2)
        self.lcdCounterWater.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdCounterWater.setObjectName(_fromUtf8("lcdCounterWater"))
        self.horizontalLayout_3.addWidget(self.lcdCounterWater)
        self.buttonPlusSoft = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPlusSoft.sizePolicy().hasHeightForWidth())
        self.buttonPlusSoft.setSizePolicy(sizePolicy)
        self.buttonPlusSoft.setMaximumSize(QtCore.QSize(50, 16777215))
        self.buttonPlusSoft.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.buttonPlusSoft.setFont(font)
        self.buttonPlusSoft.setObjectName(_fromUtf8("buttonPlusSoft"))
        self.horizontalLayout_3.addWidget(self.buttonPlusSoft)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.buttonPay = QtGui.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonPay.sizePolicy().hasHeightForWidth())
        self.buttonPay.setSizePolicy(sizePolicy)
        self.buttonPay.setMinimumSize(QtCore.QSize(0, 10))
        self.buttonPay.setBaseSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.buttonPay.setFont(font)
        self.buttonPay.setStyleSheet(_fromUtf8("color: rgb(170, 0, 0);"))
        self.buttonPay.setObjectName(_fromUtf8("buttonPay"))
        self.horizontalLayout_6.addWidget(self.buttonPay)
        self.verticalLayout.addLayout(self.horizontalLayout_6)
        self.stackedWidget.addWidget(self.pageDrinks)
        self.pagePayment = QtGui.QWidget()
        self.pagePayment.setObjectName(_fromUtf8("pagePayment"))
        self.gridLayoutWidget_3 = QtGui.QWidget(self.pagePayment)
        self.gridLayoutWidget_3.setGeometry(QtCore.QRect(6, -1, 261, 221))
        self.gridLayoutWidget_3.setObjectName(_fromUtf8("gridLayoutWidget_3"))
        self.gridLayout_3 = QtGui.QGridLayout(self.gridLayoutWidget_3)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.buttonNum1 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum1.sizePolicy().hasHeightForWidth())
        self.buttonNum1.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum1.setFont(font)
        self.buttonNum1.setObjectName(_fromUtf8("buttonNum1"))
        self.gridLayout_3.addWidget(self.buttonNum1, 1, 0, 1, 1)
        self.buttonNum3 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum3.sizePolicy().hasHeightForWidth())
        self.buttonNum3.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum3.setFont(font)
        self.buttonNum3.setObjectName(_fromUtf8("buttonNum3"))
        self.gridLayout_3.addWidget(self.buttonNum3, 1, 2, 1, 1)
        self.buttonNum4 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum4.sizePolicy().hasHeightForWidth())
        self.buttonNum4.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum4.setFont(font)
        self.buttonNum4.setObjectName(_fromUtf8("buttonNum4"))
        self.gridLayout_3.addWidget(self.buttonNum4, 2, 0, 1, 1)
        self.buttonNum5 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum5.sizePolicy().hasHeightForWidth())
        self.buttonNum5.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum5.setFont(font)
        self.buttonNum5.setObjectName(_fromUtf8("buttonNum5"))
        self.gridLayout_3.addWidget(self.buttonNum5, 2, 1, 1, 1)
        self.buttonNum6 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum6.sizePolicy().hasHeightForWidth())
        self.buttonNum6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum6.setFont(font)
        self.buttonNum6.setObjectName(_fromUtf8("buttonNum6"))
        self.gridLayout_3.addWidget(self.buttonNum6, 2, 2, 1, 1)
        self.buttonNum8 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum8.sizePolicy().hasHeightForWidth())
        self.buttonNum8.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum8.setFont(font)
        self.buttonNum8.setObjectName(_fromUtf8("buttonNum8"))
        self.gridLayout_3.addWidget(self.buttonNum8, 3, 1, 1, 1)
        self.buttonNum9 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum9.sizePolicy().hasHeightForWidth())
        self.buttonNum9.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum9.setFont(font)
        self.buttonNum9.setObjectName(_fromUtf8("buttonNum9"))
        self.gridLayout_3.addWidget(self.buttonNum9, 3, 2, 1, 1)
        self.buttonNum7 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum7.sizePolicy().hasHeightForWidth())
        self.buttonNum7.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum7.setFont(font)
        self.buttonNum7.setObjectName(_fromUtf8("buttonNum7"))
        self.gridLayout_3.addWidget(self.buttonNum7, 3, 0, 1, 1)
        self.buttonNum2 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum2.sizePolicy().hasHeightForWidth())
        self.buttonNum2.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum2.setFont(font)
        self.buttonNum2.setObjectName(_fromUtf8("buttonNum2"))
        self.gridLayout_3.addWidget(self.buttonNum2, 1, 1, 1, 1)
        self.buttonNumDel = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNumDel.sizePolicy().hasHeightForWidth())
        self.buttonNumDel.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNumDel.setFont(font)
        self.buttonNumDel.setObjectName(_fromUtf8("buttonNumDel"))
        self.gridLayout_3.addWidget(self.buttonNumDel, 4, 2, 1, 1)
        self.buttonNum0 = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNum0.sizePolicy().hasHeightForWidth())
        self.buttonNum0.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNum0.setFont(font)
        self.buttonNum0.setObjectName(_fromUtf8("buttonNum0"))
        self.gridLayout_3.addWidget(self.buttonNum0, 4, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 4, 0, 1, 1)
        self.buttonNumOk = QtGui.QPushButton(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonNumOk.sizePolicy().hasHeightForWidth())
        self.buttonNumOk.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.buttonNumOk.setFont(font)
        self.buttonNumOk.setObjectName(_fromUtf8("buttonNumOk"))
        self.gridLayout_3.addWidget(self.buttonNumOk, 5, 1, 1, 1)
        self.lcdPayment = QtGui.QLCDNumber(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.lcdPayment.sizePolicy().hasHeightForWidth())
        self.lcdPayment.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(8)
        font.setBold(False)
        font.setWeight(50)
        self.lcdPayment.setFont(font)
        self.lcdPayment.setFrameShadow(QtGui.QFrame.Raised)
        self.lcdPayment.setNumDigits(3)
        self.lcdPayment.setSegmentStyle(QtGui.QLCDNumber.Flat)
        self.lcdPayment.setObjectName(_fromUtf8("lcdPayment"))
        self.gridLayout_3.addWidget(self.lcdPayment, 0, 0, 1, 2)
        self.label = QtGui.QLabel(self.gridLayoutWidget_3)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 2, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem1, 5, 0, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem2, 5, 2, 1, 1)
        self.stackedWidget.addWidget(self.pagePayment)
        self.horizontalLayout.addWidget(self.stackedWidget)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(False)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEmpty4.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEmpty2.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEmpty1.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonRadio.setText(QtGui.QApplication.translate("MainWindow", "Radio", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonEmpty3.setText(QtGui.QApplication.translate("MainWindow", "PushButton", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonDrinks.setText(QtGui.QApplication.translate("MainWindow", "Getränke", None, QtGui.QApplication.UnicodeUTF8))
        self.labelSoft.setText(QtGui.QApplication.translate("MainWindow", "Limo/Saft", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPlusSoft.setText(QtGui.QApplication.translate("MainWindow", "+1", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonPay.setText(QtGui.QApplication.translate("MainWindow", "Bezahlen", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum1.setText(QtGui.QApplication.translate("MainWindow", "1", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum3.setText(QtGui.QApplication.translate("MainWindow", "3", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum4.setText(QtGui.QApplication.translate("MainWindow", "4", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum5.setText(QtGui.QApplication.translate("MainWindow", "5", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum6.setText(QtGui.QApplication.translate("MainWindow", "6", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum8.setText(QtGui.QApplication.translate("MainWindow", "8", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum9.setText(QtGui.QApplication.translate("MainWindow", "9", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum7.setText(QtGui.QApplication.translate("MainWindow", "7", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum2.setText(QtGui.QApplication.translate("MainWindow", "2", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNumDel.setText(QtGui.QApplication.translate("MainWindow", "löschen", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNum0.setText(QtGui.QApplication.translate("MainWindow", "0", None, QtGui.QApplication.UnicodeUTF8))
        self.buttonNumOk.setText(QtGui.QApplication.translate("MainWindow", "OK", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "EUR", None, QtGui.QApplication.UnicodeUTF8))

import resources_rc
